version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
        environment:
          JAVA_OPTS: -Xmx1536m
          GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: sdks-licenses-build-tools-extras-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew --offline --stacktrace assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
  workflows:
    version: 2
    build_test_deploy:
      jobs:
        - build
